#!/bin/bash

SCAN_DIRS=$2

case "$1" in
		
	"sources")
		find $SCAN_DIRS \( -name "*.cpp" -or -name "*.c" \) -exec basename {} \; 

	;;

	"includes")
		find $SCAN_DIRS -name "*.h" > /tmp/headers_tmp
		for i in `cat /tmp/headers_tmp`
		do	
			dirname $i >> /tmp/includes_tmp
		done
		cat /tmp/includes_tmp | sort -u > /tmp/includes_sorted_tmp
		for i in  `cat /tmp/includes_sorted_tmp | tr "\n" " "`
		do
			echo -n "-I$i "
		done
	
		rm -f /tmp/includes_tmp /tmp/includes_sorted_tmp /tmp/includes_tmp
	;;

	"sourcedirs")
		find $SCAN_DIRS \( -name "*.cpp" -or -name "*.c" \) > /tmp/sourcedirs_tmp
		for i in `cat /tmp/sourcedirs_tmp`
		do
			dirname $i >> /tmp/sourcedirs_unsorted_tmp
		done
		cat /tmp/sourcedirs_unsorted_tmp  | sort -u > /tmp/sourcedirs_sorted_tmp
		cat /tmp/sourcedirs_sorted_tmp | tr "\n" " "
		rm -f /tmp/sourcedirs_tmp /tmp/sourcedirs_unsorted_tmp /tmp/sourcedirs_sorted_tmp
esac
