name: Linux client/server build
defaults:
  run:
    shell: bash
    working-directory: platforms/premake
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Parsec client
      run: |
           export config=debug_x64
           echo "Install packages..."
           sudo apt-get update
           sudo apt-get install libsdl2-dev libsdl2-mixer-dev -y
           echo "Build Client...."
           make client
    - name: Parsec Server
      run: |
            export config=debug_x64
            make server
