name: C/C++ CI test
defaults:
  run:
    shell: bash
    working-directory: platforms/premake
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Parsec client
      run: make client
    - name: Parsec Server
      run: make server
