name: C/C++ CI test
defaults:
  run:
    shell: bash
    working-directory: platforms/premake
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Parsec client
      run: |
           echo "Install packages..."
           sudo apt-get install g++-multilib libsdl2-dev libsdl2-mixer-dev -y
           echo "Build Client...."
           make client
    - name: Parsec Server
      run: make server
