name: Build on windows.
on:
  push:
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: platforms\vs
jobs:
  build:

    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build app for release
        run: msbuild Parsec.vcxproj -t:rebuild -property:Configuration=Release /p:Platform=x64

      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with: 
          script-file: platforms\vs\openparsec.nsi
          arguments: "/V3"

      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: openparsec-installer.exe
          path: platforms\vs\openparsec-installer.exe
